# Generated by Django 5.2.5 on 2025-09-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='tasks',
        ),
    ]
